### ISSUE TITLE
Issue on installing project 

### ISSUE THREAD

**Issue by Aju100** [PythonNepal/pythonnepal.github.io#44]
Hello **Developers**, I am having the problem to install this project after cloning. I followed above **README** instructions too.

### Environment:
- Ubuntu 19.04
- Python 3.7.3 

### Description
- I have install virtualenv too and already activated too. During the installing of requriments.txt packages. All the packages didn't install due to some error.

### Solution
- Instead of ### virtualenv package, why don't we can use **pipenv**. It's good to use. I think it can be the best option for it. Thank you.

**Comment by kaflesudip** [comment]
Can u send a PR related to that?

**Comment by therj** [comment]
I really liked pipenv until I tried. Pipfile is definitely better than requirements.txt, but... it's just unfulfilled promises.
Look at [Poetry](https://poetry.eustace.io/docs/), seems better and works much like npm package (something pipenv promises, but doesn't deliver).

**Comment by amitness** [comment]
@Aju100 Can you paste the error that's thrown? "**due to some error**" is not clear enough to point out the issue.

![image](https://user-images.githubusercontent.com/8587189/64936312-f1708580-d874-11e9-96b2-820b03c1b02d.png)

**Comment by Aju100** [comment]
- Amitness Brother, All I wanted to say that I am not able to install and configure that project in my system.
![Screenshot from 2019-09-17 06-10-22](https://user-images.githubusercontent.com/29862610/65002100-ecaddf00-d911-11e9-9ff2-4c980be462b1.png)
![Screenshot from 2019-09-17 06-10-07](https://user-images.githubusercontent.com/29862610/65002106-f1729300-d911-11e9-8ff7-734d835b7d85.png)

**Comment by Aju100** [comment]
@kaflesudip brother, What does **PR** mean ???

**Comment by ksodari** [comment]
Aju Tamang, *PR* means *Pull Request.*



*With Best Regards,*
*Kuber Sodari*


*Computer/Application EngineerRakuten, Inc*

*facebook: /ksodari*
*twitter: @ksodari*

**Comment by Aju100** [comment]
thanks @ksodari

**Comment by amitness** [comment]
@Aju100 Thanks for the screenshot. From what I see, this is not an issue due to `virtualenv` and `pip` but rather due to missing dependencies required for the `cryptography` library. Popular python libraries are usually a wrapper over utilities written in C/C++ and so they need the required dependencies for compiling the actual program written in C/C++. Your system might be missing that.

Please run this command and then install from the requirements.txt again. Should work in my opinion.
```
sudo apt-get install build-essential libssl-dev libffi-dev python-dev
```
Regarding the case on `pipenv`, that's useful. If you can fork this repo, migrate current requirements.txt to pipenv and then send us a pull request, that will be useful.

**Comment by Aju100** [comment]
@amitness thanks for help.

**Comment by Aju100** [comment]
@kaflesudip @amitness  I have done PR too.
